<?php

namespace Cronixweb\Streamline\Models;

use Cronixweb\Streamline\Traits\StreamlineModel;

class Property extends StreamlineModel
{
    public function __construct(
        public readonly ?int $id = 0,
        public readonly ?int $parent_id = 0,
        public readonly ?int $search_position = 0,
        public readonly ?string $local_phone = '',
        public readonly ?string $wifi_security_key = '',
        public readonly ?int $type_id = 0,
        public readonly ?string $seo_title = '',
        public readonly ?string $seo_description = '',
        public readonly ?string $seo_keywords = '',
        public readonly ?string $addition_seo_text = '',
        public readonly ?string $mobile_seo_text = '',
        public readonly ?int $use_parent_different_owners_logic = 0,
        public readonly ?string $floor = '',
        public readonly ?int $sale_enabled = 0,
        public readonly ?int $coupons_enabled = 0,
        public readonly ?int $discounts_enabled = 0,
        public readonly ?int $longterm_enabled = 0,
        public readonly ?int $shortterm_enabled = 0,
        public readonly ?int $location_id = 0,
        public readonly ?int $building_id = 0,
        public readonly ?int $condo_type_id = 0,
        public readonly ?string $name = '',
        public readonly ?string $gallery_code = '',
        public readonly ?int $status_id = 0,
        public readonly ?string $image_ext = '',
        public readonly ?string $thumbnail_ext = '',
        public readonly ?string $unit_code = '',
        public readonly ?int $max_adults = 0,
        public readonly ?int $max_occupants = 0,
        public readonly ?int $max_pets = 0,
        public readonly ?string $virtual_tour_iframe_src = '',
        public readonly ?string $virtual_tour_iframe_style = '',
        public readonly ?string $virtual_tour_image_overlay_url = '',
        public readonly ?string $google_map_overlay_url = '',
        public readonly ?float $latitude = 0,
        public readonly ?float $longitude = 0,
        public readonly ?string $comment = '',
        public readonly ?int $housekeeping_processor_id = 0,
        public readonly ?float $location_latitude = 0,
        public readonly ?float $location_longitude = 0,
        public readonly ?int $square_foots = 0,
        public readonly ?string $floor_plan_iframe_src = '',
        public readonly ?string $floor_plan_iframe_style = '',
        public readonly ?string $web_name = '',
        public readonly ?string $status_name = '',
        public readonly ?string $location_name = '',
        public readonly ?int $company_id = 0,
        public readonly ?int $lodging_type_id = 0,
        public readonly ?int $location_area_id = 0,
        public readonly ?int $neighborhood_area_id = 0,
        public readonly ?int $resort_area_id = 0,
        public readonly ?int $home_type_id = 0,
        public readonly ?string $address = '',
        public readonly ?string $city = '',
        public readonly ?string $zip = '',
        public readonly ?string $state_name = '',
        public readonly ?string $state_description = '',
        public readonly ?string $country_name = '',
        public readonly ?string $location_area_name = '',
        public readonly ?string $neighborhood_name = '',
        public readonly ?string $location_resort_name = '',
        public readonly ?string $short_description = '',
        public readonly ?string $location_image_ext = '',
        public readonly ?string $condo_type_name = '',
        public readonly ?int $default_unit_id = 0,
        public readonly ?int $condo_type_group_id = 0,
        public readonly ?float $bathrooms_number = 0,
        public readonly ?int $bedrooms_number = 0,
        public readonly ?string $condo_type_group_name = '',
        public readonly ?string $building_short_name = '',
        public readonly ?string $building_name = '',
        public readonly ?int $images_number = 0,
        public readonly ?int $owning_type_id = 0,
        public readonly ?string $seo_page_name = '',
        public readonly ?string $view_name = '',
        public readonly ?int $view_order = 0,
        public readonly ?int $rating_count = 0,
        public readonly ?float $rating_average = 0,
        public readonly ?string $flyer_url = '',
        public readonly ?int $owning_result_table_order = 0,
        public readonly ?string $property_rating_name = '',
        public readonly ?float $property_rating_points = 0,
        public readonly ?string $home_type = '',
        public readonly ?string $email_quote_description = '',
        public readonly ?string $description = '',
        public readonly ?string $global_description = '',
        public readonly ?string $floor_name = '',
        public readonly ?int $not_show_on_website = 0,
        public readonly ?string $creation_date = '',
        public readonly ?string $property_code = '',
        public readonly ?int $housekeeping_zone_id = 0,
        public readonly ?string $region = '',
        public readonly ?string $community = '',
        public readonly ?int $online_bookings = 0,
        public readonly ?string $default_image_path = '',
        public readonly ?string $default_thumbnail_path = '',
        public readonly ?string $original_description = '',
        public readonly ?string $variable_gate_code = '',
        public readonly ?string $variable_driving_directions = '',
        public readonly ?string $variable_golf_cart = '',
        public readonly ?string $variable_trash_pick_up_days = '',
        public readonly ?string $variable_random_text = '',
        public readonly ?string $variable_trash_pick_up = '',
        public readonly ?int $variable_number_of_vehicles = 0,
        public readonly ?string $location_variable_resort_field_1 = '',
        public readonly ?string $night_gap_logic_enabled = '',
        public readonly ?int $night_gap_logic_minimal_nights = 0,
    ) {}

    public static function parse(array $data): Property
    {
        $vtSrc = null; $vtStyle = null;
        if (isset($data['virtual_tour_url']['iframe'])) {
            $vtSrc = $data['virtual_tour_url']['iframe']['src'] ?? '';
            $vtStyle = $data['virtual_tour_url']['iframe']['style'] ?? '';
        }

        $fpSrc = null; $fpStyle = null;
        if (isset($data['floor_plan_url']['iframe'])) {
            $fpSrc = $data['floor_plan_url']['iframe']['src'] ?? '';
            $fpStyle = $data['floor_plan_url']['iframe']['style'] ?? '';
        }

        $f = fn($k) => $data[$k] ?? null;
        $toInt = function ($v) { return isset($v) ? (int)$v : ''; };
        $toFloat = function ($v) { return isset($v) && is_numeric($v) ? (float)$v : ''; };

        return new Property(
            id: $toInt($f('id')),
            parent_id: $toInt($f('parent_id')),
            search_position: $toInt($f('search_position')),
            local_phone: $f('local_phone'),
            wifi_security_key: $f('wifi_security_key'),
            type_id: $toInt($f('type_id')),
            seo_title: $f('seo_title'),
            seo_description: $f('seo_description'),
            seo_keywords: $f('seo_keywords'),
            addition_seo_text: $f('addition_seo_text'),
            mobile_seo_text: $f('mobile_seo_text'),
            use_parent_different_owners_logic: $toInt($f('use_parent_different_owners_logic')),
            floor: $f('floor'),
            sale_enabled: $toInt($f('sale_enabled')),
            coupons_enabled: $toInt($f('coupons_enabled')),
            discounts_enabled: $toInt($f('discounts_enabled')),
            longterm_enabled: $toInt($f('longterm_enabled')),
            shortterm_enabled: $toInt($f('shortterm_enabled')),
            location_id: $toInt($f('location_id')),
            building_id: $toInt($f('building_id')),
            condo_type_id: $toInt($f('condo_type_id')),
            name: $f('name'),
            gallery_code: $f('gallery_code'),
            status_id: $toInt($f('status_id')),
            image_ext: $f('image_ext'),
            thumbnail_ext: $f('thumbnail_ext'),
            unit_code: $f('unit_code'),
            max_adults: $toInt($f('max_adults')),
            max_occupants: $toInt($f('max_occupants')),
            max_pets: $toInt($f('max_pets')),
            virtual_tour_iframe_src: $vtSrc,
            virtual_tour_iframe_style: $vtStyle,
            virtual_tour_image_overlay_url: $f('virtual_tour_image_overlay_url'),
            google_map_overlay_url: $f('google_map_overlay_url'),
            latitude: $toFloat($f('latitude')),
            longitude: $toFloat($f('longitude')),
            comment: $f('comment'),
            housekeeping_processor_id: $toInt($f('housekeeping_processor_id')),
            location_latitude: $toFloat($f('location_latitude')),
            location_longitude: $toFloat($f('location_longitude')),
            square_foots: $toInt($f('square_foots')),
            floor_plan_iframe_src: $fpSrc,
            floor_plan_iframe_style: $fpStyle,
            web_name: $f('web_name'),
            status_name: $f('status_name'),
            location_name: $f('location_name'),
            company_id: $toInt($f('company_id')),
            lodging_type_id: $toInt($f('lodging_type_id')),
            location_area_id: $toInt($f('location_area_id')),
            neighborhood_area_id: $toInt($f('neighborhood_area_id')),
            resort_area_id: $toInt($f('resort_area_id')),
            home_type_id: $toInt($f('home_type_id')),
            address: $f('address'),
            city: $f('city'),
            zip: $f('zip'),
            state_name: $f('state_name'),
            state_description: $f('state_description'),
            country_name: $f('country_name'),
            location_area_name: $f('location_area_name'),
            neighborhood_name: $f('neighborhood_name'),
            location_resort_name: $f('location_resort_name'),
            short_description: $f('short_description'),
            location_image_ext: $f('location_image_ext'),
            condo_type_name: $f('condo_type_name'),
            default_unit_id: $toInt($f('default_unit_id')),
            condo_type_group_id: $toInt($f('condo_type_group_id')),
            bathrooms_number: $toFloat($f('bathrooms_number')),
            bedrooms_number: $toInt($f('bedrooms_number')),
            condo_type_group_name: $f('condo_type_group_name'),
            building_short_name: $f('building_short_name'),
            building_name: $f('building_name'),
            images_number: $toInt($f('images_number')),
            owning_type_id: $toInt($f('owning_type_id')),
            seo_page_name: $f('seo_page_name'),
            view_name: $f('view_name'),
            view_order: $toInt($f('view_order')),
            rating_count: $toInt($f('rating_count')),
            rating_average: $toFloat($f('rating_average')),
            flyer_url: $f('flyer_url'),
            owning_result_table_order: $toInt($f('owning_result_table_order')),
            property_rating_name: $f('property_rating_name'),
            property_rating_points: $toFloat($f('property_rating_points')),
            home_type: $f('home_type'),
            email_quote_description: $f('email_quote_description'),
            description: $f('description'),
            global_description: $f('global_description'),
            floor_name: $f('floor_name'),
            not_show_on_website: $toInt($f('not_show_on_website')),
            creation_date: $f('creation_date'),
            property_code: $f('property_code'),
            housekeeping_zone_id: $toInt($f('housekeeping_zone_id')),
            region: $f('region'),
            community: $f('community'),
            online_bookings: $toInt($f('online_bookings')),
            default_image_path: $f('default_image_path'),
            default_thumbnail_path: $f('default_thumbnail_path'),
            original_description: $f('original_description'),
            variable_gate_code: $f('variable_gate_code'),
            variable_driving_directions: $f('variable_driving_directions'),
            variable_golf_cart: $f('variable_golf_cart'),
            variable_trash_pick_up_days: $f('variable_trash_pick_up_days'),
            variable_random_text: $f('variable_random_text'),
            variable_trash_pick_up: $f('variable_trash_pick_up'),
            variable_number_of_vehicles: $toInt($f('variable_number_of_vehicles')),
            location_variable_resort_field_1: $f('location_variable_resort_field_1'),
            night_gap_logic_enabled: $f('night_gap_logic_enabled'),
            night_gap_logic_minimal_nights: $toInt($f('night_gap_logic_minimal_nights')),
        );
    }
}